DROP TABLE IF EXISTS sensors_data;

CREATE TABLE sensors_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    topic TEXT NOT NULL,
    data TEXT NOT NULL
);
